name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run a simple test
      id: simple-test
      run: |
        echo "Hello from GitHub Actions!"
        echo "test_output=Hello from GitHub Actions!" >> $GITHUB_OUTPUT

    - name: Microsoft Teams Notification
      uses: skitionek/notify-microsoft-teams@master
      if: always()
      with:
        webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
        needs: ${{ toJson(needs) }}
        job: ${{ toJson(job) }}
        steps: ${{ toJson(steps) }}
        title: 'Test output: ${{ steps.simple-test.outputs.test_output }}'
