name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run a simple test
      id: simple-test
      run: |
        cp sample-sca-results.sarif "${{ runner.temp }}/sca-results.sarif"

    - name: Microsoft Teams Notification (Custom Action)
      uses: ./.github/actions/custom-teams-action
      if: always()
      with:
        webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
        title: "test title"
        sarif_file: ${{ runner.temp }}/sca-results.sarif
